/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type IdentifierPlateDto = {
    /**
     * @type string
    */
    type: string;
    /**
     * @type number
    */
    IdentifiersPlatesID: number;
    /**
     * @type string
    */
    Serial: string;
    /**
     * @type string
    */
    platesType: string;
    /**
     * @type boolean
    */
    Done: boolean;
    /**
     * @type string
    */
    QrCode: string;
    /**
     * @type string
    */
    CodCliente: string;
};