/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { IdentifierPlateDto } from "./IdentifierPlateDto";
import type { PartNameDto } from "./PartNameDto";

export type ListPlatesResponseDto = {
    /**
     * @type number
    */
    ProductionID: number;
    /**
     * @type number
    */
    priority: number;
    /**
     * @type string
    */
    OrderNum: string;
    /**
     * @type string
    */
    PartCode: string;
    /**
     * @type object
    */
    PartName: PartNameDto;
    /**
     * @type number
    */
    PlanQty: number;
    /**
     * @type string
    */
    PlannedEndTimestamp: string;
    /**
     * @type array
    */
    Identifiersplates: IdentifierPlateDto[];
};