/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export enum ListPlatesFiltersDtoModeEnum {
    all = "all",
    avaiable = "avaiable",
    notavaiable = "notavaiable"
}

export type ListPlatesFiltersDto = {
    /**
     * @type number | undefined
    */
    page?: number;
    /**
     * @type number | undefined
    */
    limit?: number;
    /**
     * @description Número de série da placa
     * @type string | undefined
    */
    serialNumber?: string;
    /**
     * @description ID da placa de identificação
     * @type number | undefined
    */
    identifiersPlatesID?: number;
    /**
     * @description Número da ordem de produção
     * @type string | undefined
    */
    orderNum?: string;
    /**
     * @description Código da peça
     * @type string | undefined
    */
    partCode?: string;
    /**
     * @description Modo de filtragem por disponibilidade
     * @default "all"
     * @type string | undefined
    */
    mode?: ListPlatesFiltersDtoModeEnum;
};