/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ModelNestDto = {
    /**
     * @type string
    */
    type: string;
    /**
     * @type number
    */
    ModelNestId: number;
    /**
     * @type string, date-time
    */
    SeverTime: Date;
    /**
     * @type string
    */
    Name: string;
    /**
     * @type number
    */
    Lote: number;
    /**
     * @type string
    */
    FilePath: string;
    /**
     * @type string
    */
    Gabarito: string;
};