/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Serviço de entrega reiniciado com sucesso
*/
export type NestControllerRestartScript200 = any;

/**
 * @description Falha ao reiniciar o serviço de entrega
*/
export type NestControllerRestartScript500 = any;

export type NestControllerRestartScriptMutationResponse = NestControllerRestartScript200;

export type NestControllerRestartScriptMutation = {
    Response: NestControllerRestartScript200;
    Errors: NestControllerRestartScript500;
};