/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Serviço de entrega reiniciado com sucesso
*/
export type NestControllerCreateBaseNest200 = any;

/**
 * @description Falha ao reiniciar o serviço de entrega
*/
export type NestControllerCreateBaseNest500 = any;

export type NestControllerCreateBaseNestMutationResponse = NestControllerCreateBaseNest200;

export type NestControllerCreateBaseNestMutation = {
    Response: NestControllerCreateBaseNest200;
    Errors: NestControllerCreateBaseNest500;
};