/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type NestScriptresponseDTO = {
    /**
     * @type string
    */
    data: string;
    /**
     * @type boolean
    */
    current: boolean;
};