/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { NestScriptresponseDTO } from "./NestScriptresponseDTO";

export type NestControllerGetScript200 = NestScriptresponseDTO[];

/**
 * @description Falha ao buscar scripts
*/
export type NestControllerGetScript500 = any;

export type NestControllerGetScriptQueryResponse = NestControllerGetScript200;

export type NestControllerGetScriptQuery = {
    Response: NestControllerGetScript200;
    Errors: NestControllerGetScript500;
};