/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserNestResponseDto } from "./UserNestResponseDto";

export type NestControllerGetCurrentNestsMethod200 = UserNestResponseDto;

/**
 * @description Falha ao buscar nests ativos
*/
export type NestControllerGetCurrentNestsMethod500 = any;

export type NestControllerGetCurrentNestsMethodQueryResponse = NestControllerGetCurrentNestsMethod200;

export type NestControllerGetCurrentNestsMethodQuery = {
    Response: NestControllerGetCurrentNestsMethod200;
    Errors: NestControllerGetCurrentNestsMethod500;
};