/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserNestResponseDto } from "./UserNestResponseDto";

export type NestControllerRemoveCurrentNestMethod200 = UserNestResponseDto;

/**
 * @description Não existe nest ativo para remover
*/
export type NestControllerRemoveCurrentNestMethod400 = any;

/**
 * @description Falha interna ao remover o nest ativo
*/
export type NestControllerRemoveCurrentNestMethod500 = any;

export type NestControllerRemoveCurrentNestMethodMutationResponse = NestControllerRemoveCurrentNestMethod200;

export type NestControllerRemoveCurrentNestMethodMutation = {
    Response: NestControllerRemoveCurrentNestMethod200;
    Errors: NestControllerRemoveCurrentNestMethod400 | NestControllerRemoveCurrentNestMethod500;
};