/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserNestResponseDto } from "./UserNestResponseDto";

export type NestControllerAutoRunMethod200 = UserNestResponseDto;

/**
 * @description Não existe placas disponiveis para nest ou já existe um nest ativo
*/
export type NestControllerAutoRunMethod400 = any;

/**
 * @description Falha interna ao processar o nest automático
*/
export type NestControllerAutoRunMethod500 = any;

export type NestControllerAutoRunMethodMutationResponse = NestControllerAutoRunMethod200;

export type NestControllerAutoRunMethodMutation = {
    Response: NestControllerAutoRunMethod200;
    Errors: NestControllerAutoRunMethod400 | NestControllerAutoRunMethod500;
};