/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ManipulateScriptDto } from "./ManipulateScriptDto";

/**
 * @description Script manipulado com sucesso
*/
export type NestControllerManipulateScript200 = any;

/**
 * @description Falha ao manipular script
*/
export type NestControllerManipulateScript500 = any;

export type NestControllerManipulateScriptMutationRequest = ManipulateScriptDto;

export type NestControllerManipulateScriptMutationResponse = NestControllerManipulateScript200;

export type NestControllerManipulateScriptMutation = {
    Response: NestControllerManipulateScript200;
    Request: NestControllerManipulateScriptMutationRequest;
    Errors: NestControllerManipulateScript500;
};