/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ListPlatesDeliveryResponseDto } from "./ListPlatesDeliveryResponseDto";

export type PaginatedListPlatesDeliveryResponseDtoDto = {
    /**
     * @type number
    */
    total: number;
    /**
     * @type number
    */
    page: number;
    /**
     * @type number
    */
    limit: number;
    /**
     * @type number
    */
    totalPages: number;
    /**
     * @description Lista de itens paginados do tipo ListPlatesDeliveryResponseDto.
     * @type array
    */
    data: ListPlatesDeliveryResponseDto[];
};