/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PartNameDto = {
    /**
     * @type string
    */
    data: string;
    /**
     * @type string
    */
    description: string;
    /**
     * @type string
    */
    itemCliente: string;
    /**
     * @type string
    */
    revision: string;
};