/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProductionDto } from "./ProductionDto";

/**
 * @description Placas removidas com sucesso
*/
export type PlatesControllerDeletePlate200 = any;

/**
 * @description As placas para essa ordem não foram geradas ou o plano já começou a ser feito
*/
export type PlatesControllerDeletePlate400 = any;

/**
 * @description A producao nao foi encontrada
*/
export type PlatesControllerDeletePlate404 = any;

/**
 * @description Problemas ao remover as plaquinhas
*/
export type PlatesControllerDeletePlate500 = any;

export type PlatesControllerDeletePlateMutationRequest = ProductionDto;

export type PlatesControllerDeletePlateMutationResponse = PlatesControllerDeletePlate200;

export type PlatesControllerDeletePlateMutation = {
    Response: PlatesControllerDeletePlate200;
    Request: PlatesControllerDeletePlateMutationRequest;
    Errors: PlatesControllerDeletePlate400 | PlatesControllerDeletePlate404 | PlatesControllerDeletePlate500;
};