/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ChangePlatesFifoDTO } from "./ChangePlatesFifoDTO";

/**
 * @description Prioridade da placa alterada com sucesso
*/
export type PlatesControllerChangePlatesFifo200 = any;

/**
 * @description Productionid informada não é válida
*/
export type PlatesControllerChangePlatesFifo400 = any;

/**
 * @description Problemas ao subir a prioridade
*/
export type PlatesControllerChangePlatesFifo500 = any;

export type PlatesControllerChangePlatesFifoMutationRequest = ChangePlatesFifoDTO;

export type PlatesControllerChangePlatesFifoMutationResponse = PlatesControllerChangePlatesFifo200;

export type PlatesControllerChangePlatesFifoMutation = {
    Response: PlatesControllerChangePlatesFifo200;
    Request: PlatesControllerChangePlatesFifoMutationRequest;
    Errors: PlatesControllerChangePlatesFifo400 | PlatesControllerChangePlatesFifo500;
};