/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { IdentifierPlateDto } from "./IdentifierPlateDto";

export type PlatesControllerReworkPlatePathParams = {
    /**
     * @type number
    */
    idPlate: number;
};

export type PlatesControllerReworkPlate200 = IdentifierPlateDto;

/**
 * @description A placa nao foi feita ainda entao nao pode ser gerado retrabalho
*/
export type PlatesControllerReworkPlate400 = any;

/**
 * @description O id passado não existe
*/
export type PlatesControllerReworkPlate404 = any;

/**
 * @description Não foi possível refazer a placa para gravação
*/
export type PlatesControllerReworkPlate500 = any;

export type PlatesControllerReworkPlateMutationResponse = PlatesControllerReworkPlate200;

export type PlatesControllerReworkPlateMutation = {
    Response: PlatesControllerReworkPlate200;
    PathParams: PlatesControllerReworkPlatePathParams;
    Errors: PlatesControllerReworkPlate400 | PlatesControllerReworkPlate404 | PlatesControllerReworkPlate500;
};