/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PlatesControllerDeleteSinglePlatePathParams = {
    /**
     * @type number
    */
    idPlate: number;
};

/**
 * @description Placa removida com sucesso
*/
export type PlatesControllerDeleteSinglePlate200 = any;

/**
 * @description A placa não é um retrabalho excluível, já foi feita ou possui nest ativo
*/
export type PlatesControllerDeleteSinglePlate400 = any;

/**
 * @description A placa informada não foi encontrada
*/
export type PlatesControllerDeleteSinglePlate404 = any;

/**
 * @description Problemas ao remover a plaquinha
*/
export type PlatesControllerDeleteSinglePlate500 = any;

export type PlatesControllerDeleteSinglePlateMutationResponse = PlatesControllerDeleteSinglePlate200;

export type PlatesControllerDeleteSinglePlateMutation = {
    Response: PlatesControllerDeleteSinglePlate200;
    PathParams: PlatesControllerDeleteSinglePlatePathParams;
    Errors: PlatesControllerDeleteSinglePlate400 | PlatesControllerDeleteSinglePlate404 | PlatesControllerDeleteSinglePlate500;
};