/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PaginatedListPlatesDeliveryResponseDtoDto } from "./PaginatedListPlatesDeliveryResponseDtoDto";

export enum PlatesDeliveryControllerListQueryParamsStatusEnum {
    delivered = "delivered",
    pending = "pending"
}

export type PlatesDeliveryControllerListQueryParams = {
    /**
     * @type number | undefined
    */
    page?: number;
    /**
     * @type number | undefined
    */
    limit?: number;
    /**
     * @description Número de série da placa
     * @type string | undefined
    */
    serialNumber?: string;
    /**
     * @description ID da placa de identificação
     * @type number | undefined
    */
    identifiersPlatesID?: number;
    /**
     * @description Número da ordem de produção
     * @type string | undefined
    */
    orderNum?: string;
    /**
     * @description Código da peça
     * @type string | undefined
    */
    partCode?: string;
    /**
     * @description Nome do produto
     * @type string | undefined
    */
    productName?: string;
    /**
     * @description Status da entrega; todas as placas retornadas já estão concluídas.
     * @default "pending"
     * @type string | undefined
    */
    status?: PlatesDeliveryControllerListQueryParamsStatusEnum;
};

export type PlatesDeliveryControllerList200 = PaginatedListPlatesDeliveryResponseDtoDto;

export type PlatesDeliveryControllerListQueryResponse = PlatesDeliveryControllerList200;

export type PlatesDeliveryControllerListQuery = {
    Response: PlatesDeliveryControllerList200;
    QueryParams: PlatesDeliveryControllerListQueryParams;
    Errors: any;
};