/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PaginatedListPlatesResponseDtoDto } from "./PaginatedListPlatesResponseDtoDto";

export enum PlatesControllerListPlatesQueryParamsModeEnum {
    all = "all",
    avaiable = "avaiable",
    notavaiable = "notavaiable"
}

export type PlatesControllerListPlatesQueryParams = {
    /**
     * @type number | undefined
    */
    page?: number;
    /**
     * @type number | undefined
    */
    limit?: number;
    /**
     * @description Número de série da placa
     * @type string | undefined
    */
    serialNumber?: string;
    /**
     * @description ID da placa de identificação
     * @type number | undefined
    */
    identifiersPlatesID?: number;
    /**
     * @description Número da ordem de produção
     * @type string | undefined
    */
    orderNum?: string;
    /**
     * @description Código da peça
     * @type string | undefined
    */
    partCode?: string;
    /**
     * @description Modo de filtragem por disponibilidade
     * @default "all"
     * @type string | undefined
    */
    mode?: PlatesControllerListPlatesQueryParamsModeEnum;
};

export type PlatesControllerListPlates200 = PaginatedListPlatesResponseDtoDto;

export type PlatesControllerListPlatesQueryResponse = PlatesControllerListPlates200;

export type PlatesControllerListPlatesQuery = {
    Response: PlatesControllerListPlates200;
    QueryParams: PlatesControllerListPlatesQueryParams;
    Errors: any;
};