/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlatesDelivery } from "./PlatesDelivery";
import type { RegisterPlatesDeliveryDto } from "./RegisterPlatesDeliveryDto";

export type PlatesDeliveryControllerRegister201 = PlatesDelivery;

/**
 * @description O plano informado não foi encontrado
*/
export type PlatesDeliveryControllerRegister404 = any;

/**
 * @description Este plano já foi entregue
*/
export type PlatesDeliveryControllerRegister409 = any;

export type PlatesDeliveryControllerRegisterMutationRequest = RegisterPlatesDeliveryDto;

export type PlatesDeliveryControllerRegisterMutationResponse = PlatesDeliveryControllerRegister201;

export type PlatesDeliveryControllerRegisterMutation = {
    Response: PlatesDeliveryControllerRegister201;
    Request: PlatesDeliveryControllerRegisterMutationRequest;
    Errors: PlatesDeliveryControllerRegister404 | PlatesDeliveryControllerRegister409;
};