/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { IdentifierPlateDto } from "./IdentifierPlateDto";
import type { ProductionDto } from "./ProductionDto";

export type PlatesControllerCreatePlate200 = IdentifierPlateDto[];

/**
 * @description O plano não pode ser gerado porque já foi gerado antes ou porque faltam conversão, serialização ou dados obrigatórios do item
*/
export type PlatesControllerCreatePlate400 = any;

/**
 * @description Não foi possível localizar o plano informado para gerar as plaquinhas
*/
export type PlatesControllerCreatePlate404 = any;

/**
 * @description Não foi possível gerar as plaquinhas deste plano agora
*/
export type PlatesControllerCreatePlate500 = any;

export type PlatesControllerCreatePlateMutationRequest = ProductionDto;

export type PlatesControllerCreatePlateMutationResponse = PlatesControllerCreatePlate200;

export type PlatesControllerCreatePlateMutation = {
    Response: PlatesControllerCreatePlate200;
    Request: PlatesControllerCreatePlateMutationRequest;
    Errors: PlatesControllerCreatePlate400 | PlatesControllerCreatePlate404 | PlatesControllerCreatePlate500;
};