/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { IdentifierPlateDto } from "./IdentifierPlateDto";
import type { ProductionDto } from "./ProductionDto";

export type PlatesControllerCreatePlate200 = IdentifierPlateDto[];

/**
 * @description As placas para essa ordem já foram geradas
*/
export type PlatesControllerCreatePlate400 = any;

/**
 * @description A producao nao foi encontrada
*/
export type PlatesControllerCreatePlate404 = any;

/**
 * @description Problemas ao gerar as plaquinhas
*/
export type PlatesControllerCreatePlate500 = any;

export type PlatesControllerCreatePlateMutationRequest = ProductionDto;

export type PlatesControllerCreatePlateMutationResponse = PlatesControllerCreatePlate200;

export type PlatesControllerCreatePlateMutation = {
    Response: PlatesControllerCreatePlate200;
    Request: PlatesControllerCreatePlateMutationRequest;
    Errors: PlatesControllerCreatePlate400 | PlatesControllerCreatePlate404 | PlatesControllerCreatePlate500;
};