/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ProductionControllerRequestOrders200 = any;

export type ProductionControllerRequestOrdersQueryResponse = ProductionControllerRequestOrders200;

export type ProductionControllerRequestOrdersQuery = {
    Response: ProductionControllerRequestOrders200;
    Errors: any;
};