/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type RegisterPlatesDeliveryDto = {
    /**
     * @description ProductionID do plano que está sendo entregue
     * @type number
    */
    ProductionID: number;
    /**
     * @description Nome ou identificação do separador que retirou as plaquinhas
     * @type string
    */
    Separator: string;
};