/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { IdentifierPlateDto } from "./IdentifierPlateDto";
import type { ModelNestDto } from "./ModelNestDto";

export type UserNestResponseDto = {
    /**
     * @type number
    */
    UserNestID: number;
    /**
     * @type string, date-time
    */
    SeverTime: Date;
    /**
     * @type boolean
    */
    done: boolean;
    /**
     * @type string
    */
    Name: string;
    /**
     * @type array
    */
    IdentifierPlates: IdentifierPlateDto[];
    /**
     * @type object
    */
    ModelNest: ModelNestDto;
};