/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/client";
import type { NestControllerManipulateScriptMutationRequest, NestControllerManipulateScriptMutationResponse, NestControllerManipulateScript500 } from "../models/NestControllerManipulateScript";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/client";

function getNestControllerManipulateScriptUrl() {
  const res = { method: 'POST', url: `https://fiberlaser.ethos.ind.br/api/nest/script` as const }
  return res
}

/**
 * {@link /api/nest/script}
 */
export async function nestControllerManipulateScript(data: NestControllerManipulateScriptMutationRequest, config: Partial<RequestConfig<NestControllerManipulateScriptMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<NestControllerManipulateScriptMutationResponse, ResponseErrorConfig<NestControllerManipulateScript500>, NestControllerManipulateScriptMutationRequest>({ method : "POST", url : getNestControllerManipulateScriptUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}