/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/client";
import type { NestControllerGetScriptQueryResponse, NestControllerGetScript500 } from "../models/NestControllerGetScript";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/client";

function getNestControllerGetScriptUrl() {
  const res = { method: 'GET', url: `https://fiberlaser.ethos.ind.br/api/nest/script` as const }
  return res
}

/**
 * {@link /api/nest/script}
 */
export async function nestControllerGetScript(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<NestControllerGetScriptQueryResponse, ResponseErrorConfig<NestControllerGetScript500>, unknown>({ method : "GET", url : getNestControllerGetScriptUrl().url.toString(), ... requestConfig })
  return res.data
}