/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/client";
import type { NestControllerRemoveCurrentNestMethodMutationResponse, NestControllerRemoveCurrentNestMethod400, NestControllerRemoveCurrentNestMethod500 } from "../models/NestControllerRemoveCurrentNestMethod";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/client";

function getNestControllerRemoveCurrentNestMethodUrl() {
  const res = { method: 'POST', url: `https://fiberlaser.ethos.ind.br/api/nest/remove` as const }
  return res
}

/**
 * {@link /api/nest/remove}
 */
export async function nestControllerRemoveCurrentNestMethod(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<NestControllerRemoveCurrentNestMethodMutationResponse, ResponseErrorConfig<NestControllerRemoveCurrentNestMethod400 | NestControllerRemoveCurrentNestMethod500>, unknown>({ method : "POST", url : getNestControllerRemoveCurrentNestMethodUrl().url.toString(), ... requestConfig })
  return res.data
}