/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/client";
import type { NestControllerCreateBaseNestMutationResponse, NestControllerCreateBaseNest500 } from "../models/NestControllerCreateBaseNest";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/client";

function getNestControllerCreateBaseNestUrl() {
  const res = { method: 'POST', url: `http://192.168.99.129:9192/nest/script/restart` as const }
  return res
}

/**
 * {@link /nest/script/restart}
 */
export async function nestControllerCreateBaseNest(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<NestControllerCreateBaseNestMutationResponse, ResponseErrorConfig<NestControllerCreateBaseNest500>, unknown>({ method : "POST", url : getNestControllerCreateBaseNestUrl().url.toString(), ... requestConfig })
  return res.data
}