/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/client";
import type { NestControllerRestartScriptMutationResponse, NestControllerRestartScript500 } from "../models/NestControllerRestartScript";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/client";

function getNestControllerRestartScriptUrl() {
  const res = { method: 'POST', url: `http://192.168.99.129:9192/nest/script/restart` as const }
  return res
}

/**
 * {@link /nest/script/restart}
 */
export async function nestControllerRestartScript(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<NestControllerRestartScriptMutationResponse, ResponseErrorConfig<NestControllerRestartScript500>, unknown>({ method : "POST", url : getNestControllerRestartScriptUrl().url.toString(), ... requestConfig })
  return res.data
}