/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/client";
import type { NestControllerAutoRunMethodMutationResponse, NestControllerAutoRunMethod400, NestControllerAutoRunMethod500 } from "../models/NestControllerAutoRunMethod";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/client";

function getNestControllerAutoRunMethodUrl() {
  const res = { method: 'POST', url: `http://192.168.99.129:9192/nest/run` as const }
  return res
}

/**
 * {@link /nest/run}
 */
export async function nestControllerAutoRunMethod(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<NestControllerAutoRunMethodMutationResponse, ResponseErrorConfig<NestControllerAutoRunMethod400 | NestControllerAutoRunMethod500>, unknown>({ method : "POST", url : getNestControllerAutoRunMethodUrl().url.toString(), ... requestConfig })
  return res.data
}