/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/client";
import type { NestControllerGetCurrentNestsMethodQueryResponse, NestControllerGetCurrentNestsMethod500 } from "../models/NestControllerGetCurrentNestsMethod";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/client";

function getNestControllerGetCurrentNestsMethodUrl() {
  const res = { method: 'GET', url: `https://fiberlaser.ethos.ind.br/api/nest/current` as const }
  return res
}

/**
 * {@link /api/nest/current}
 */
export async function nestControllerGetCurrentNestsMethod(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<NestControllerGetCurrentNestsMethodQueryResponse, ResponseErrorConfig<NestControllerGetCurrentNestsMethod500>, unknown>({ method : "GET", url : getNestControllerGetCurrentNestsMethodUrl().url.toString(), ... requestConfig })
  return res.data
}