/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/client";
import type { PlatesControllerReworkPlateMutationResponse, PlatesControllerReworkPlatePathParams, PlatesControllerReworkPlate400, PlatesControllerReworkPlate404, PlatesControllerReworkPlate500 } from "../models/PlatesControllerReworkPlate";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/client";

function getPlatesControllerReworkPlateUrl(idPlate: PlatesControllerReworkPlatePathParams["idPlate"]) {
  const res = { method: 'POST', url: `http://192.168.99.129:9192/plates/${idPlate}/rework` as const }
  return res
}

/**
 * {@link /plates/:idPlate/rework}
 */
export async function platesControllerReworkPlate(idPlate: PlatesControllerReworkPlatePathParams["idPlate"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<PlatesControllerReworkPlateMutationResponse, ResponseErrorConfig<PlatesControllerReworkPlate400 | PlatesControllerReworkPlate404 | PlatesControllerReworkPlate500>, unknown>({ method : "POST", url : getPlatesControllerReworkPlateUrl(idPlate).url.toString(), ... requestConfig })
  return res.data
}