/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/client";
import type { PlatesDeliveryControllerRegisterMutationRequest, PlatesDeliveryControllerRegisterMutationResponse, PlatesDeliveryControllerRegister404, PlatesDeliveryControllerRegister409 } from "../models/PlatesDeliveryControllerRegister";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/client";

function getPlatesDeliveryControllerRegisterUrl() {
  const res = { method: 'POST', url: `https://fiberlaser.ethos.ind.br/api/delivery/plates` as const }
  return res
}

/**
 * {@link /api/delivery/plates}
 */
export async function platesDeliveryControllerRegister(data: PlatesDeliveryControllerRegisterMutationRequest, config: Partial<RequestConfig<PlatesDeliveryControllerRegisterMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<PlatesDeliveryControllerRegisterMutationResponse, ResponseErrorConfig<PlatesDeliveryControllerRegister404 | PlatesDeliveryControllerRegister409>, PlatesDeliveryControllerRegisterMutationRequest>({ method : "POST", url : getPlatesDeliveryControllerRegisterUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}