/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/client";
import type { PlatesDeliveryControllerListQueryResponse, PlatesDeliveryControllerListQueryParams } from "../models/PlatesDeliveryControllerList";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/client";

function getPlatesDeliveryControllerListUrl() {
  const res = { method: 'GET', url: `https://fiberlaser.ethos.ind.br/api/delivery/plates` as const }
  return res
}

/**
 * {@link /api/delivery/plates}
 */
export async function platesDeliveryControllerList(params?: PlatesDeliveryControllerListQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<PlatesDeliveryControllerListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getPlatesDeliveryControllerListUrl().url.toString(), params, ... requestConfig })
  return res.data
}