/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/client";
import type { PlatesControllerDeletePlateMutationRequest, PlatesControllerDeletePlateMutationResponse, PlatesControllerDeletePlate400, PlatesControllerDeletePlate404, PlatesControllerDeletePlate500 } from "../models/PlatesControllerDeletePlate";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/client";

function getPlatesControllerDeletePlateUrl() {
  const res = { method: 'DELETE', url: `https://fiberlaser.ethos.ind.br/api/plates` as const }
  return res
}

/**
 * {@link /api/plates}
 */
export async function platesControllerDeletePlate(data: PlatesControllerDeletePlateMutationRequest, config: Partial<RequestConfig<PlatesControllerDeletePlateMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<PlatesControllerDeletePlateMutationResponse, ResponseErrorConfig<PlatesControllerDeletePlate400 | PlatesControllerDeletePlate404 | PlatesControllerDeletePlate500>, PlatesControllerDeletePlateMutationRequest>({ method : "DELETE", url : getPlatesControllerDeletePlateUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}