/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/client";
import type { PlatesControllerCreatePlateMutationRequest, PlatesControllerCreatePlateMutationResponse, PlatesControllerCreatePlate400, PlatesControllerCreatePlate404, PlatesControllerCreatePlate500 } from "../models/PlatesControllerCreatePlate";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/client";

function getPlatesControllerCreatePlateUrl() {
  const res = { method: 'POST', url: `http://192.168.99.129:9192/plates` as const }
  return res
}

/**
 * {@link /plates}
 */
export async function platesControllerCreatePlate(data: PlatesControllerCreatePlateMutationRequest, config: Partial<RequestConfig<PlatesControllerCreatePlateMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<PlatesControllerCreatePlateMutationResponse, ResponseErrorConfig<PlatesControllerCreatePlate400 | PlatesControllerCreatePlate404 | PlatesControllerCreatePlate500>, PlatesControllerCreatePlateMutationRequest>({ method : "POST", url : getPlatesControllerCreatePlateUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}