/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/client";
import type { PlatesControllerDeleteSinglePlateMutationResponse, PlatesControllerDeleteSinglePlatePathParams, PlatesControllerDeleteSinglePlate400, PlatesControllerDeleteSinglePlate404, PlatesControllerDeleteSinglePlate500 } from "../models/PlatesControllerDeleteSinglePlate";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/client";

function getPlatesControllerDeleteSinglePlateUrl(idPlate: PlatesControllerDeleteSinglePlatePathParams["idPlate"]) {
  const res = { method: 'DELETE', url: `http://192.168.99.129:9192/plates/${idPlate}` as const }
  return res
}

/**
 * {@link /plates/:idPlate}
 */
export async function platesControllerDeleteSinglePlate(idPlate: PlatesControllerDeleteSinglePlatePathParams["idPlate"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<PlatesControllerDeleteSinglePlateMutationResponse, ResponseErrorConfig<PlatesControllerDeleteSinglePlate400 | PlatesControllerDeleteSinglePlate404 | PlatesControllerDeleteSinglePlate500>, unknown>({ method : "DELETE", url : getPlatesControllerDeleteSinglePlateUrl(idPlate).url.toString(), ... requestConfig })
  return res.data
}