/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/client";
import type { PlatesControllerChangePlatesFifoMutationRequest, PlatesControllerChangePlatesFifoMutationResponse, PlatesControllerChangePlatesFifo400, PlatesControllerChangePlatesFifo500 } from "../models/PlatesControllerChangePlatesFifo";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/client";

function getPlatesControllerChangePlatesFifoUrl() {
  const res = { method: 'POST', url: `http://192.168.99.129:9192/plates/fifo` as const }
  return res
}

/**
 * {@link /plates/fifo}
 */
export async function platesControllerChangePlatesFifo(data: PlatesControllerChangePlatesFifoMutationRequest, config: Partial<RequestConfig<PlatesControllerChangePlatesFifoMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<PlatesControllerChangePlatesFifoMutationResponse, ResponseErrorConfig<PlatesControllerChangePlatesFifo400 | PlatesControllerChangePlatesFifo500>, PlatesControllerChangePlatesFifoMutationRequest>({ method : "POST", url : getPlatesControllerChangePlatesFifoUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}