/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/client";
import type { PlatesControllerListPlatesQueryResponse, PlatesControllerListPlatesQueryParams } from "../models/PlatesControllerListPlates";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/client";

function getPlatesControllerListPlatesUrl() {
  const res = { method: 'GET', url: `http://192.168.99.129:9192/plates` as const }
  return res
}

/**
 * {@link /plates}
 */
export async function platesControllerListPlates(params?: PlatesControllerListPlatesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<PlatesControllerListPlatesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getPlatesControllerListPlatesUrl().url.toString(), params, ... requestConfig })
  return res.data
}