/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/client";
import type { ProductionControllerRequestOrdersQueryResponse } from "../models/ProductionControllerRequestOrders";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/client";

function getProductionControllerRequestOrdersUrl() {
  const res = { method: 'GET', url: `https://fiberlaser.ethos.ind.br/api/production` as const }
  return res
}

/**
 * {@link /api/production}
 */
export async function productionControllerRequestOrders(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<ProductionControllerRequestOrdersQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getProductionControllerRequestOrdersUrl().url.toString(), ... requestConfig })
  return res.data
}